stages:
  - build
  - tests

job_test:
  stage: tests
  image: node
  script:
    - npm install
    - npm run test
    - npx prettier --check .

job_build:
stage: build
  image: node
  script:
    - npm install
    - npm run build